name: CI

on:
  push:
    branches: ['**']
    paths-ignore: [CHANGELOG.md]
    tags-ignore: ['**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalr00ts/action-pre-commit@v0
